### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by shimonmagal** [pquerna/protoc-gen-dynamo#15]
Hi,

I was wondering if this project is being maintained. 
I think the idea of generating "entities" that are easily read and written to Dynamo is great, but I see that the documentation isn't aligned with the working example -
https://github.com/pquerna/protoc-gen-dynamo/blob/main/examplepb/example.proto

and in this working example, I am not sure why the section is defined twice -

  option (dynamo.msg).key = {
    pk_fields: [
      "id",
      "country",
      "foo"
    ]
    sk_const: "example"
  };
  option (dynamo.msg).key = {
    pk_fields: [
      "id",
      "country",
      "foo"
    ]
    sk_const: "dummyvalue"
  };
  
  with all that is changing is the sk_const.
  
  Some better documentation can be nice.
  I don't mind helping by documenting myself, btw.
  
  Thank you

**Comment by pquerna** [comment]
Yes, the docs are outdated.

We changed how Primary Keys vs GSIs work.

So, each key message, the first Key is the object primary key.

Each one after than is `gsiN`.  So the second block is `gsi1`, the third is `gsi2`.  The Key is rendered as `gsiNpk` and `gsiNsk`...

We are using this project in production, and its working great.  We just haven't updated the README.
